USE master
GO

CREATE TABLE BOOK
(BookID INT PRIMARY KEY,Title VARCHAR(50), PublisherName VARCHAR(50))

CREATE TABLE BOOK_AUTHORS
(BookID INT, AuthorName VARCHAR(50))

CREATE TABLE PUBLISHER
(Name VARCHAR(50),Address VARCHAR(30),Phone VARCHAR(12))

CREATE TABLE BOOK_COPIES
(BookID INT, BranchID INT, No_Of_Copies INT)

CREATE TABLE BOOK_LOANS
(BookID INT, BranchID INT, CardNO INT, DateOUT Date, DueDate Date)

CREATE TABLE LIBRARY_BRANCH
(BranchID INT, BranchName VARCHAR(30), Address VARCHAR(30))

CREATE TABLE BORROWER
(CardNO INT, Name VARCHAR(30), Address VARCHAR(30), Phone VARCHAR(12))
