SELECT SUM(BOOK_COPIES.No_Of_Copies) AS 'Total Number of Books'
FROM BOOK INNER JOIN BOOK_COPIES
	ON BOOK.BookID=BOOK_COPIES.BookID
FULL JOIN LIBRARY_BRANCH ON BOOK_COPIES.BranchID=LIBRARY_BRANCH.BranchID
WHERE BOOK.Title='The Lost Tribe'