DECLARE @Size INT
SET @Size=5

SELECT BORROWER.Name,BORROWER.[Address],Count(BOOK_LOANS.BookID) AS 'Total Books Checked'
FROM BORROWER INNER JOIN BOOK_LOANS ON BORROWER.CardNO=BOOK_LOANS.CardNO
WHERE BOOK_LOANS.BookID>@Size
GROUP BY BORROWER.Name,BORROWER.[Address]

